// ui_kits/app-svelte/src/components/SimulatorBanner.svelte
<!--
  SimulatorBanner — applied from source-evidence/capitalizarme-boilerplate-html/components/Hero.astro's layout, with
  ContactForm.astro's real copy ("Averigua tu capacidad de inversión").
-->
<section class="mx-auto max-w-[1440px] px-6 lg:px-[140px] py-16 lg:py-20">
  <div class="flex flex-col md:flex-row items-center gap-10 lg:gap-16">
    <div class="max-w-[480px]">
      <h1 class="font-display font-extrabold text-5xl lg:text-6xl text-brand-navy">
        Averigua tu capacidad de inversión
      </h1>
      <p class="mt-4 text-brand-navy/70">
        Descubre hasta qué monto puedes invertir acorde a tu situación financiera y para qué
        propiedades te alcanza — sin compromiso.
      </p>
      <a
        href="#"
        class="inline-block mt-6 font-cta font-bold uppercase tracking-wider text-sm rounded-full bg-brand-blue text-white px-8 py-3 hover:opacity-90 transition-all duration-300 ease-in-out"
      >
        Agenda tu reunión
      </a>
    </div>
    <img src="/assets/mascot/capi-searching.png" alt="Capi buscando propiedades" class="max-w-sm w-full h-auto" />
  </div>
</section>

// ui_kits/app-react/components/SimulatorBanner.jsx
// SimulatorBanner — applied from Hero.astro + ContactForm.astro copy ("Averigua tu capacidad de inversión")
function SimulatorBanner() {
  return (
    <section className="container section simulator-banner">
      <div className="row">
        <div className="copy">
          <h1>Averigua tu capacidad de inversión</h1>
          <p>
            Descubre hasta qué monto puedes invertir acorde a tu situación financiera y para qué
            propiedades te alcanza — sin compromiso.
          </p>
          <a className="btn btn-primary" href="#">Agenda tu reunión</a>
        </div>
        <img src="../../assets/mascot/capi-searching.png" alt="Capi buscando propiedades" />
      </div>
    </section>
  );
}
window.SimulatorBanner = SimulatorBanner;
