// ui_kits/app-react/components/Footer.jsx
// Footer — applied verbatim from Footer.astro, including the compliance disclaimer (DESIGN.md §8).
function Footer() {
  return (
    <footer className="app-footer">
      <div className="container">
        <div className="cols">
          <div><p className="col-title">Invierte</p><ul><li><a className="footer-link" href="#">Explorar inversiones</a></li></ul></div>
          <div><p className="col-title">Aprende</p><ul><li><a className="footer-link" href="#">Primeros pasos de inversión</a></li></ul></div>
          <div><p className="col-title">Ayuda y soporte</p><ul><li><a className="footer-link" href="#">Centro de ayuda</a></li></ul></div>
          <div><p className="col-title">Comunidad</p><ul><li><a className="footer-link" href="#">Comunidad</a></li></ul></div>
          <div>
            <p className="col-title">Síguenos</p>
            <ul>
              <li><a className="social-link" href="#">Facebook</a></li>
              <li><a className="social-link" href="#">Instagram</a></li>
              <li><a className="social-link" href="#">Youtube</a></li>
              <li><a className="social-link" href="#">Twitter</a></li>
              <li><a className="social-link" href="#">Linkedin</a></li>
            </ul>
          </div>
        </div>
        <div className="bottom-row">
          <img src="../../assets/logo/horizontal/070726_logo-capitalizarme-negro-sin-com.png" alt="Capitalizarme" />
          <div className="legal">
            <p>Todas las rentabilidades y retornos mostrados en la página son referenciales, los rendimientos pasados no garantizan retornos futuros.</p>
            <p>©Capitalizarme 2026 • Condiciones de uso • Políticas de privacidad</p>
            <p>Hendaya 60, OF. 901 Las Condes.</p>
          </div>
        </div>
      </div>
    </footer>
  );
}
window.Footer = Footer;

// ui_kits/app-svelte/src/components/Footer.svelte
<!--
  Footer — applied from source-evidence/capitalizarme-boilerplate-html/components/Footer.astro, including the compliance
  disclaimer required by DESIGN.md §8.
-->
<footer class="border-t border-gray-100 mt-16">
  <div class="mx-auto max-w-[1440px] px-6 lg:px-[140px] py-16">
    <div class="grid grid-cols-2 md:grid-cols-5 gap-10">
      <div>
        <p class="text-sm font-bold uppercase tracking-wider text-brand-navy mb-3">Invierte</p>
        <ul class="flex flex-col gap-2"><li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Explorar inversiones</a></li></ul>
      </div>
      <div>
        <p class="text-sm font-bold uppercase tracking-wider text-brand-navy mb-3">Aprende</p>
        <ul class="flex flex-col gap-2"><li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Primeros pasos de inversión</a></li></ul>
      </div>
      <div>
        <p class="text-sm font-bold uppercase tracking-wider text-brand-navy mb-3">Ayuda y soporte</p>
        <ul class="flex flex-col gap-2"><li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Centro de ayuda</a></li></ul>
      </div>
      <div>
        <p class="text-sm font-bold uppercase tracking-wider text-brand-navy mb-3">Comunidad</p>
        <ul class="flex flex-col gap-2"><li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Comunidad</a></li></ul>
      </div>
      <div>
        <p class="text-sm font-bold uppercase tracking-wider text-brand-navy mb-3">Síguenos</p>
        <ul class="flex flex-col gap-2">
          <li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Facebook</a></li>
          <li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Instagram</a></li>
          <li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Youtube</a></li>
          <li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Twitter</a></li>
          <li><a href="#" class="text-sm text-brand-navy/70 hover:text-brand-blue">Linkedin</a></li>
        </ul>
      </div>
    </div>
    <div class="flex flex-col md:flex-row items-center md:items-end justify-between gap-6 mt-12 pt-8 border-t border-gray-50">
      <img src="/assets/logo/horizontal/070726_logo-capitalizarme-negro-sin-com.png" alt="Capitalizarme" class="w-40 h-auto" />
      <div class="text-[10px] text-brand-navy/50 text-center md:text-right leading-relaxed">
        <p>Todas las rentabilidades y retornos mostrados en la página son referenciales, los rendimientos pasados no garantizan retornos futuros.</p>
        <p>©Capitalizarme 2026 • Condiciones de uso • Políticas de privacidad</p>
        <p>Hendaya 60, OF. 901 Las Condes.</p>
      </div>
    </div>
  </div>
</footer>
